package net.placemarkt.yamlconverter

import com.squareup.kotlinpoet.FileSpec
import kotlin.contracts.ExperimentalContracts
import kotlin.contracts.InvocationKind
import kotlin.contracts.contract

@OptIn(ExperimentalContracts::class)
inline fun generatedFileSpec(
    fileName: String,
    packageName: String = "net.placemarkt.generated",
    block: FileSpec.Builder.() -> Unit,
): FileSpec {
    contract {
        callsInPlace(block, InvocationKind.EXACTLY_ONCE)
    }
    return FileSpec.builder(packageName = packageName, fileName = fileName)
        .addFileComment("THIS FILE IS AUTOGENERATED, PLEASE DON'T CHANGE IT MANUALLY")
        .apply(block)
        .build()
}
