name: Test and Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4.1.3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GLS_OCTOCAT_TOKEN }}
          submodules: true

      - name: Checkout repo
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4.1.3

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Update formats
        if: github.event_name == 'pull_request'
        run: ./gradlew :YamlConverter:run

      - name: Add address format changes
        id: update_format
        if: github.event_name == 'pull_request'
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: 'gls-octocat'
          author_email: 'github@gls-ecl.com'
          message: 'Update address formats'

      - name: Fail on updated
        if: steps.update_format.outputs.committed == 'true'
        run: exit 1

      - name: Test and Build
        run: ./gradlew build

      - name: Test Publication
        run: ./gradlew publishAddressFormatterPublicationToMavenLocal
