name: Publish to Maven Central
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-14
    timeout-minutes: 20

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version-file: .github/.java-version

      - name: Set VCS tag
        id: variables
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Publish to Maven central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signReleaseEnabled: true
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PUBLISH_GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PUBLISH_GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PUBLISH_GPG_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          VCS_TAG: ${{ steps.variables.outputs.tag }}
