name: Publish on GitHub Packages
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3

      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Publish on GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
