name: Publish on GitHub Packages
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Publish on GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
