name: Publish on GitHub Packages
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set VCS tag
        id: variables
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Publish on GitHub Packages
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signReleaseEnabled: true
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PUBLISH_GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PUBLISH_GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PUBLISH_GPG_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          VCS_TAG: ${{ steps.variables.outputs.tag }}
